baseURL: 'http://phish.dev/'
languageCode: 'en-ca'
title: 'ğŸŸdev'
theme: "papermod"

params:
    homeInfoParams:
      Title: "ğŸ  phish.dev"

    socialIcons:
      - name: "GitHub"
        url: "https://github.com/phish-dev"